nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5173', 'https://jonathan-turpin.fr']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 1800
    paths:
        '^/auth/':
            allow_origin: ['http://localhost:5173', 'https://jonathan-turpin.fr']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'OPTIONS']
            max_age: 1800
        '^/':
            allow_origin: ['http://localhost:5173', 'https://jonathan-turpin.fr']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'OPTIONS']
            max_age: 1800